version: 1.2
workflows:
  - name: SingleSampleQc
    subclass: WDL
    primaryDescriptorPath: /SingleSampleQc.wdl

  - name: SingleSampleQcMoveResult
    subclass: WDL
    primaryDescriptorPath: /SingleSampleQcMoveResult.wdl
